name: CI

on:
  # Run on all pull requests that change code.
  pull_request:
    paths-ignore:
      - 'README.md'
      - LICENSE
      - .editorconfig
  # Run every time a code change is pushed.
  push:
    paths-ignore:
      - 'README.md'
      - LICENSE
      - .editorconfig
  # Test if things still work each Tuesday morning at 5:39 UTC.
  # This way we will catch incompatible pandoc changes in a timely
  # manner.
  schedule:
    # At 3:47am each Thursday
    - cron: '47 3 * * 4'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        pandoc:
          #- edge # uncomment to catch errors faster
          - latest
          # - 2.19.2

    container:
      image: pandoc/core:${{ matrix.pandoc }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: apk add make

      - name: Test
        run: make ptest BUILD=false
