name: Publish Manual

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches: ['main']
    paths-ignore:
      - 'README.md'
      - LICENSE
      - .editorconfig

jobs:
  manual:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Prepare custom pandoc container
        run: |
          docker build -t custom-pandoc -f .tools/Dockerfile .
      - name: Render Website
        run: |
          make -B website \
            SOURCE_DIR="" \
            PANDOC="docker run --rm --volume $(pwd):/data \
              --user $(id -u):$(id -g) custom-pandoc"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
